# https://github.com/acyortjs/demo.git 为存放网站文件项目地址
# https://github.com/acyortjs/theme-donob.git themes/donob 为博客主题，如果你使用默认主题则可以去掉这句
# ${GH_TOKEN} 为你在 travis-ci 设置的变量
# public 为在 config.yml 设置的 public_dir 目录
# 注意修改这里提交的用户名，邮箱
# 这里提交的分支是 gh-pages，根据你的实际情况修改

language: node_js

node_js: 6.0.0

install:
  - npm install acyort -g

before_script:
  ##- git clone https://github.com/lchiffon/newBlog.git public # public 这个目录跟你的 config.yml 设置一样
  ##- cd public
  ##- git checkout gh-pages

script:
  ##- cd ../
  ##- acyort init
  ##- cp config.bak.yml config.yml
  ##- cat config.yml
  ##- rm config.bak.yml
  # - git clone https://github.com/acyortjs/theme-donob.git themes/donob # 如果使用默认主题，可以不要这句
  - acyort build

after_script:
  #- cd public
  - git add .
  - git config user.name "lchiffon" # 注意修改用户名
  - git config user.email "chiffonlang@icloud.com" # 注意修改邮箱
  - git commit -m "update from travis-ci"
  - git push https://${GH_TOKEN}@github.com/lchiffon/newBlog.git master:master # 注意项目地址及分支名，这里的例子分支是 `gh-pages`
